'use client'

import Button, { ButtonTheme } from '@/shared/ui/Button/Button'
import { Layout } from '@/widgets/Layout'

export default function Page() {
	return (
		<Layout>
			<div>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.FILL}>dasdasdadasadadas</Button>
				<Button theme={ButtonTheme.OUTLINE}>dasdasdadasadadas</Button>
			</div>
		</Layout>
	)
}
