export const getRouteMain = () => '/'
export const getRouteAbout = () => '/about'
export const getRouteProfile = () => `/profile`
export const getRouteLogin = () => `/auth/login`
export const getRouteSignUp = () => `/auth/sign-up`
export const getRouteForgotPassword = () => `/auth/forgot-password`
export const getSettingsRoute = () => `/i/settings`
export const getDashboardRoute = () => `/i`
export const getSupportRoute = () => `/support`
